import { createContext, useContext, useState, useEffect } from 'react';

const ContextoIdioma = createContext();

const traducciones = {
  es: {
    // Navegación
    nav_inicio: 'Inicio',
    nav_diario: 'Diario',
    nav_registros: 'Registros',
    nav_estadisticas: 'Estadísticas',
    nav_habitos: 'Hábitos',
    nav_meditacion: 'Meditación',
    nav_ranked: 'Ránking',
    nav_calendario: 'Calendario',
    nav_usuario: 'Usuario',

    // Comunes
    guardar: 'Guardar',
    cancelar: 'Cancelar',
    confirmar: 'Confirmar',
    cargando: 'Cargando...',
    error: 'Error',
    exito: '¡Éxito!',

    // Pantalla Usuario
    perfil: 'Perfil',
    datos_personales: 'Datos Personales',
    seguridad: 'Seguridad',
    idioma: 'Idioma',
    galeria: 'Galería',
    acerca_de: 'Acerca de',
    terminos: 'Términos',
    exportar: 'Exportar Datos',
    modo_oscuro: 'Modo Oscuro',
    modo_claro: 'Modo Claro',
    cerrar_sesion: 'Cerrar Sesión',
    actualizar_clave: 'Actualizar Clave',
    zona_peligro: 'Zona de Peligro',
    eliminar_cuenta: 'Eliminar Cuenta Permanente',
    
    // Diario
    diario_titulo: '¿Cómo va tu día?',
    diario_placeholder: 'Cuéntame algo...',
    diario_sueno: 'Horas de sueño',
    diario_animo: 'Estado de ánimo',
    diario_multimedia: 'Multimedia',
    
    // Estadísticas
    stats_titulo: 'Tu Progreso',
    stats_animo_medio: 'Ánimo Medio',
    stats_sueno_medio: 'Sueño Medio',
    stats_racha_max: 'Racha Máxima',

    // Meditación
    med_titulo: 'Momento de Calma',
    med_comenzar: 'Comenzar Sesión',
    med_finalizada: '¡Sesión Completada!',
    med_minutos: 'Minutos',
    med_tecnica: 'Técnica de Respiración',
    med_musica: 'Música Ambiental',
    
    // Tooltips de Estadísticas
    tooltip_comparativa: 'Muestra tu promedio de ánimo actual y cómo ha cambiado respecto al periodo anterior, además de tus mejores rachas.',
    tooltip_consistencia: 'Mapa de calor que visualiza los días que has completado cada uno de tus hábitos activos.',
    tooltip_impacto: 'Compara tu nivel de ánimo en los días que cumples un hábito (línea azul) frente a los que no (línea dorada), para identificar qué rutinas mejoran más tu bienestar. Cuanto más hacia fuera esté la línea azul, mayor impacto positivo.',
    tooltip_bienestar: 'Gráfico de línea que muestra la evolución diaria de tu estado de ánimo a lo largo del tiempo.',
    tooltip_clima: 'Distribución porcentual de tus estados de ánimo (desde fatal hasta genial) en el periodo seleccionado.',
    tooltip_descanso: 'Analiza la relación entre las horas dormidas y tu humor. El tamaño del punto indica el nivel de ánimo.',
    tooltip_paz: 'Seguimiento de tus minutos de meditación diarios y las técnicas de respiración más utilizadas.',

    // --- LANDING PAGE ---
    landing_nav_iniciar: 'Iniciar Sesión',
    landing_nav_empezar: 'Empezar',
    landing_hero_mejor: 'Tu mejor versión.',
    landing_hero_dia: 'Cada día.',
    landing_hero_desc: 'Diario emocional, hábitos gamificados, meditación y estadísticas avanzadas en una sola plataforma.',
    landing_hero_gratis: 'Comenzar gratis',
    landing_hero_cuenta: 'Ya tengo cuenta',
    landing_hero_tarjeta: 'Sin tarjeta necesaria',
    landing_features_titulo: 'Todo lo que necesitas',
    landing_features_subtitulo: '6 módulos integrados. Una sola plataforma. Cero fricciones.',
    landing_feat_diario_title: 'Diario Emocional',
    landing_feat_diario_desc: 'Registra tu estado de ánimo, pensamientos y horas de sueño cada día. Adjunta fotos y notas de voz.',
    landing_feat_habitos_title: 'Hábitos Gamificados',
    landing_feat_habitos_desc: 'Crea hábitos, diarias y tareas. Gana XP por completarlas y mantén tus rachas al máximo.',
    landing_feat_stats_title: 'Estadísticas Inteligentes',
    landing_feat_stats_desc: 'Correlaciones ánimo-sueño, consistencia de hábitos y tendencias con gráficos interactivos.',
    landing_feat_med_title: 'Meditación Guiada',
    landing_feat_med_desc: 'Técnicas de respiración y sonidos ambiente. Temporizador integrado y seguimiento de sesiones.',
    landing_feat_cal_title: 'Calendario Visual',
    landing_feat_cal_desc: 'Revisa tu historial día a día con un mapa de calor de emociones y resúmenes diarios.',
    landing_feat_ranks_title: 'Sistema de Rangos',
    landing_feat_ranks_desc: 'Desde "Sin Rango" hasta "Rubí I". Asciende en la jerarquía de ligas con tu disciplina.',
    landing_intel_tag: 'Inteligencia de Datos',
    landing_intel_titulo_1: 'Tus datos cuentan una ',
    landing_intel_titulo_2: 'historia',
    landing_intel_desc: 'Descubre cómo tu sueño afecta tu ánimo, qué hábitos te hacen más productivo y cuáles son tus patrones emocionales a lo largo del tiempo.',
    landing_intel_bullet_1: 'Correlación entre sueño y estado de ánimo',
    landing_intel_bullet_2: 'Mapas de calor de consistencia de hábitos',
    landing_intel_bullet_3: 'Análisis de tendencias por período',
    landing_intel_bullet_4: 'Estadísticas comparativas dinámicas',
    landing_gami_titulo_1: 'Mejora en la ',
    landing_gami_titulo_2: 'Vida Real',
    landing_gami_desc: 'Trata tu vida como un RPG. Completa hábitos, gana XP y asciende de liga.',
    landing_gami_xp_title: 'Gana XP',
    landing_gami_xp_desc: 'Cada hábito completado te recompensa con puntos de experiencia.',
    landing_gami_liga_title: 'Sube de Liga',
    landing_gami_liga_desc: 'Acumula XP para ascender a través de 9 ligas únicas.',
    landing_gami_racha_title: 'Mantén Rachas',
    landing_gami_racha_desc: 'La consistencia es clave. Tus rachas potencian tu motivación.',
    landing_gami_unete: 'Únete a la competición',
    landing_cta_titulo: 'Empieza hoy.',
    landing_cta_desc: 'Tu mejor versión está a un clic de distancia.',
    landing_cta_crear: 'Crear mi cuenta',
    landing_footer_acerca: 'Sobre el Proyecto',
    landing_footer_terminos: 'Términos',
    landing_footer_error: 'Reportar error',
    landing_modal_acerca_titulo: 'Sobre el Proyecto',
    landing_modal_mision_title: 'Nuestra Misión',
    landing_modal_mision_desc: 'ImproveMe es una plataforma integral diseñada para facilitar el autoconocimiento y el crecimiento personal. Nace de la necesidad de tener un espacio privado y seguro donde registrar no solo lo que hacemos, sino cómo nos sentimos, ayudando a identificar patrones de comportamiento y mejorar nuestra calidad de vida día a día.',
    landing_modal_chars_title: 'Características Principales',
    landing_modal_chars_1: 'Registro diario de emociones y pensamientos.',
    landing_modal_chars_2: 'Seguimiento de hábitos saludables (sueño, meditación, etc.).',
    landing_modal_chars_3: 'Soporte multimedia: guarda tus recuerdos en voz e imagen.',
    landing_modal_chars_4: 'Análisis de progreso mediante estadísticas detalladas.',
    landing_modal_tec_title: 'Tecnología',
    landing_modal_tec_desc: 'Este proyecto ha sido desarrollado utilizando tecnologías modernas como React para el frontend, Tailwind CSS para un diseño premium y Node.js con Prisma para una gestión de datos eficiente y segura.',
    landing_modal_footer: 'ImproveMe © 2026 · Tu mejor versión empieza hoy',
    landing_modal_term_titulo: 'Términos y Condiciones',
    landing_modal_term_1_title: '1. Aceptación de los Términos',
    landing_modal_term_1_desc: 'Al utilizar ImproveMe, aceptas cumplir con estos términos. Esta aplicación está diseñada para el crecimiento personal y el registro de hábitos.',
    landing_modal_term_2_title: '2. Privacidad de los Datos',
    landing_modal_term_2_desc: 'Tus registros diarios, audios e imágenes se almacenan de forma segura. ImproveMe no comparte tu información personal con terceros sin tu consentimiento explícito.',
    landing_modal_term_3_title: '3. Uso Responsable',
    landing_modal_term_3_desc: 'Te comprometes a utilizar la aplicación de manera constructiva. El contenido multimedia subido debe respetar las normas de convivencia y legalidad vigente.',
    landing_modal_term_4_title: '4. Propiedad Intelectual',
    landing_modal_term_4_desc: 'Toda la propiedad intelectual de la aplicación ImproveMe pertenece a sus desarrolladores. El contenido que subas sigue siendo de tu propiedad.',
    landing_modal_term_5_title: '5. Modificaciones',
    landing_modal_term_5_desc: 'Nos reservamos el derecho de modificar estos términos en cualquier momento. Se te notificará de cualquier cambio significativo.',
    landing_modal_term_act: 'Última actualización: 22 de Abril de 2026',
    landing_modal_err_titulo: 'Reportar Error',
    landing_modal_err_sub: 'Ayúdanos a mejorar ImproveMe',
    landing_modal_err_sis: 'Información del Sistema',
    landing_modal_err_nav: 'Navegador',
    landing_modal_err_plat: 'Plataforma',
    landing_modal_err_res: 'Resolución',
    landing_modal_err_idioma: 'Idioma',
    landing_modal_err_inc: 'Descripción de la Incidencia',
    landing_modal_err_placeholder: 'Describe detalladamente qué estabas haciendo y qué error has detectado...',
    landing_modal_err_nota: 'Al enviar, se generará un reporte para la administración de la plataforma con estos datos técnicos adjuntos.',
    landing_modal_err_btn: 'Enviar Reporte',
    landing_modal_err_enviando: 'Enviando...',
    landing_modal_err_enviado: '¡Enviado!',

    // --- AUTENTICACIÓN ---
    auth_volver: 'Volver',
    auth_tema_claro: 'Cambiar a modo claro',
    auth_tema_oscuro: 'Cambiar a modo oscuro',
    auth_bienvenido: 'Bienvenido de nuevo',
    auth_inicia: 'Inicia sesión para continuar',
    auth_crea: 'Crea tu cuenta',
    auth_viaje: 'Comienza tu viaje de mejora',
    auth_separador: 'o continúa con',
    auth_usuario: 'Usuario',
    auth_usuario_placeholder: 'Tu alias',
    auth_email: 'Email',
    auth_email_placeholder: 'tu@email.com',
    auth_pass: 'Contraseña',
    auth_pass_placeholder: '••••••••',
    auth_btn_entrar: 'Entrar a ImproveMe',
    auth_btn_crear: 'Crear Cuenta',
    auth_cargando: 'Procesando...',
    auth_no_cuenta: '¿No tienes cuenta?',
    auth_ya_miembro: '¿Ya eres miembro?',
    auth_registrate: 'Regístrate aquí',
    auth_inicia_link: 'Inicia Sesión',
    auth_error_credenciales: 'Email y contraseña son obligatorios',
    auth_error_registro: 'Todos los campos son obligatorios',
    auth_error_pass_corta: 'La contraseña debe tener al menos 8 caracteres',
    auth_error_sesion_exp: 'Sesión expirada',
    auth_error_login: 'Error al iniciar sesión',
    auth_error_singup: 'Error al registrarse',
    auth_error_sinc: 'Error al sincronizar datos',
    auth_error_google: 'Error al iniciar sesión con Google',
  },
  en: {
    // Navigation
    nav_inicio: 'Home',
    nav_diario: 'Journal',
    nav_registros: 'Logs',
    nav_estadisticas: 'Stats',
    nav_habitos: 'Habits',
    nav_meditacion: 'Meditation',
    nav_ranked: 'Ranking',
    nav_calendario: 'Calendar',
    nav_usuario: 'User',

    // Common
    guardar: 'Save',
    cancelar: 'Cancel',
    confirmar: 'Confirm',
    cargando: 'Loading...',
    error: 'Error',
    exito: 'Success!',

    // User Screen
    perfil: 'Profile',
    datos_personales: 'Personal Data',
    seguridad: 'Security',
    idioma: 'Language',
    galeria: 'Gallery',
    acerca_de: 'About',
    terminos: 'Terms',
    exportar: 'Export Data',
    modo_oscuro: 'Dark Mode',
    modo_claro: 'Light Mode',
    cerrar_sesion: 'Logout',
    actualizar_clave: 'Update Password',
    zona_peligro: 'Danger Zone',
    eliminar_cuenta: 'Delete Account Permanently',

    // Journal
    diario_titulo: 'How is your day?',
    diario_placeholder: 'Tell me something...',
    diario_sueno: 'Sleep hours',
    diario_animo: 'Mood',
    diario_multimedia: 'Multimedia',

    // Stats
    stats_titulo: 'Your Progress',
    stats_animo_medio: 'Average Mood',
    stats_sueno_medio: 'Average Sleep',
    stats_racha_max: 'Max Streak',

    // Meditation
    med_titulo: 'Calm Moment',
    med_comenzar: 'Start Session',
    med_finalizada: 'Session Completed!',
    med_minutos: 'Minutes',
    med_tecnica: 'Breathing Technique',
    med_musica: 'Ambient Music',

    // Stats Tooltips
    tooltip_comparativa: 'Shows your current average mood and how it has changed compared to the previous period, along with your best streaks.',
    tooltip_consistencia: 'Heatmap visualizing the days you have completed each of your active habits.',
    tooltip_impacto: "Compares your mood level on days you complete a habit (blue line) vs those you don't (gold line), to identify which routines improve your well-being most. The further out the blue line is, the greater the positive impact.",
    tooltip_bienestar: 'Line chart showing the daily evolution of your mood over time.',
    tooltip_clima: 'Percentage distribution of your moods (from fatal to great) in the selected period.',
    tooltip_descanso: 'Analyzes the relationship between sleep hours and your mood. Point size indicates the mood level.',
    tooltip_paz: 'Tracking of your daily meditation minutes and most used breathing techniques.',

    // --- LANDING PAGE ---
    landing_nav_iniciar: 'Log In',
    landing_nav_empezar: 'Get Started',
    landing_hero_mejor: 'Your best version.',
    landing_hero_dia: 'Every day.',
    landing_hero_desc: 'Emotional journal, gamified habits, meditation, and advanced stats in a single platform.',
    landing_hero_gratis: 'Get started for free',
    landing_hero_cuenta: 'I already have an account',
    landing_hero_tarjeta: 'No credit card required',
    landing_features_titulo: 'Everything you need',
    landing_features_subtitulo: '6 integrated modules. One platform. Zero friction.',
    landing_feat_diario_title: 'Emotional Journal',
    landing_feat_diario_desc: 'Track your mood, thoughts, and sleep hours daily. Attach photos and voice notes.',
    landing_feat_habitos_title: 'Gamified Habits',
    landing_feat_habitos_desc: 'Create habits, dailies, and tasks. Earn XP for completing them and keep your streaks to the max.',
    landing_feat_stats_title: 'Smart Statistics',
    landing_feat_stats_desc: 'Mood-sleep correlations, habit consistency, and trends with interactive charts.',
    landing_feat_med_title: 'Guided Meditation',
    landing_feat_med_desc: 'Breathing techniques and ambient sounds. Integrated timer and session tracking.',
    landing_feat_cal_title: 'Visual Calendar',
    landing_feat_cal_desc: 'Review your history day by day with an emotion heatmap and daily summaries.',
    landing_feat_ranks_title: 'League System',
    landing_feat_ranks_desc: 'From "No Rank" to "Ruby I". Rise through the league hierarchy with your discipline.',
    landing_intel_tag: 'Data Intelligence',
    landing_intel_titulo_1: 'Your data tells a ',
    landing_intel_titulo_2: 'story',
    landing_intel_desc: 'Discover how your sleep affects your mood, which habits make you more productive, and what your emotional patterns are over time.',
    landing_intel_bullet_1: 'Correlation between sleep and mood',
    landing_intel_bullet_2: 'Habit consistency heatmaps',
    landing_intel_bullet_3: 'Trends analysis by period',
    landing_intel_bullet_4: 'Dynamic comparative statistics',
    landing_gami_titulo_1: 'Improve in ',
    landing_gami_titulo_2: 'Real Life',
    landing_gami_desc: 'Treat your life like an RPG. Complete habits, earn XP, and climb through leagues.',
    landing_gami_xp_title: 'Earn XP',
    landing_gami_xp_desc: 'Each completed habit rewards you with experience points.',
    landing_gami_liga_title: 'Level Up',
    landing_gami_liga_desc: 'Accumulate XP to climb through 9 unique leagues.',
    landing_gami_racha_title: 'Keep Streaks',
    landing_gami_racha_desc: 'Consistency is key. Your streaks boost your motivation.',
    landing_gami_unete: 'Join the competition',
    landing_cta_titulo: 'Start today.',
    landing_cta_desc: 'Your best version is just a click away.',
    landing_cta_crear: 'Create my account',
    landing_footer_acerca: 'About the Project',
    landing_footer_terminos: 'Terms',
    landing_footer_error: 'Report error',
    landing_modal_acerca_titulo: 'About the Project',
    landing_modal_mision_title: 'Our Mission',
    landing_modal_mision_desc: 'ImproveMe is an all-in-one platform designed to facilitate self-knowledge and personal growth. It is born from the need to have a private and secure space to register not only what we do, but how we feel, helping to identify behavior patterns and improve our quality of life day by day.',
    landing_modal_chars_title: 'Key Features',
    landing_modal_chars_1: 'Daily tracking of emotions and thoughts.',
    landing_modal_chars_2: 'Healthy habits tracking (sleep, meditation, etc.).',
    landing_modal_chars_3: 'Multimedia support: save your memories in voice and image.',
    landing_modal_chars_4: 'Progress analysis through detailed statistics.',
    landing_modal_tec_title: 'Technology',
    landing_modal_tec_desc: 'This project has been developed using modern technologies such as React for the frontend, Tailwind CSS for a premium design, and Node.js with Prisma for efficient and secure data management.',
    landing_modal_footer: 'ImproveMe © 2026 · Your best version starts today',
    landing_modal_term_titulo: 'Terms and Conditions',
    landing_modal_term_1_title: '1. Acceptance of Terms',
    landing_modal_term_1_desc: 'By using ImproveMe, you agree to comply with these terms. This app is designed for personal growth and habit tracking.',
    landing_modal_term_2_title: '2. Data Privacy',
    landing_modal_term_2_desc: 'Your daily logs, audio, and images are stored securely. ImproveMe does not share your personal information with third parties without your explicit consent.',
    landing_modal_term_3_title: '3. Responsible Use',
    landing_modal_term_3_desc: 'You agree to use the application constructively. Uploaded multimedia content must respect rules of conduct and current laws.',
    landing_modal_term_4_title: '4. Intellectual Property',
    landing_modal_term_4_desc: 'All intellectual property of the ImproveMe application belongs to its developers. The content you upload remains yours.',
    landing_modal_term_5_title: '5. Modifications',
    landing_modal_term_5_desc: 'We reserve the right to modify these terms at any time. You will be notified of any significant changes.',
    landing_modal_term_act: 'Last updated: April 22, 2026',
    landing_modal_err_titulo: 'Report Error',
    landing_modal_err_sub: 'Help us improve ImproveMe',
    landing_modal_err_sis: 'System Information',
    landing_modal_err_nav: 'Browser',
    landing_modal_err_plat: 'Platform',
    landing_modal_err_res: 'Resolution',
    landing_modal_err_idioma: 'Language',
    landing_modal_err_inc: 'Incident Description',
    landing_modal_err_placeholder: 'Describe in detail what you were doing and what error you detected...',
    landing_modal_err_nota: 'Upon submission, a report will be generated for the platform administration with these technical details attached.',
    landing_modal_err_btn: 'Submit Report',
    landing_modal_err_enviando: 'Submitting...',
    landing_modal_err_enviado: 'Submitted!',

    // --- AUTENTICACIÓN ---
    auth_volver: 'Go back',
    auth_tema_claro: 'Change to light mode',
    auth_tema_oscuro: 'Change to dark mode',
    auth_bienvenido: 'Welcome back',
    auth_inicia: 'Log in to continue',
    auth_crea: 'Create your account',
    auth_viaje: 'Begin your self-improvement journey',
    auth_separador: 'or continue with',
    auth_usuario: 'Username',
    auth_usuario_placeholder: 'Your alias',
    auth_email: 'Email',
    auth_email_placeholder: 'your@email.com',
    auth_pass: 'Password',
    auth_pass_placeholder: '••••••••',
    auth_btn_entrar: 'Enter ImproveMe',
    auth_btn_crear: 'Create Account',
    auth_cargando: 'Processing...',
    auth_no_cuenta: "Don't have an account?",
    auth_ya_miembro: 'Already a member?',
    auth_registrate: 'Sign up here',
    auth_inicia_link: 'Log In',
    auth_error_credenciales: 'Email and password are required',
    auth_error_registro: 'All fields are required',
    auth_error_pass_corta: 'Password must be at least 8 characters long',
    auth_error_sesion_exp: 'Session expired',
    auth_error_login: 'Error logging in',
    auth_error_singup: 'Error signing up',
    auth_error_sinc: 'Error synchronizing data',
    auth_error_google: 'Error logging in with Google',
  },
  fr: {
    // Navigation
    nav_inicio: 'Accueil',
    nav_diario: 'Journal',
    nav_registros: 'Journaux',
    nav_estadisticas: 'Statistiques',
    nav_habitos: 'Habitudes',
    nav_meditacion: 'Méditation',
    nav_ranked: 'Classement',
    nav_calendario: 'Calendrier',
    nav_usuario: 'Utilisateur',

    // Common
    guardar: 'Sauvegarder',
    cancelar: 'Annuler',
    confirmar: 'Confirmer',
    cargando: 'Chargement...',
    error: 'Erreur',
    exito: 'Succès !',

    // User Screen
    perfil: 'Profil',
    datos_personales: 'Données Personnelles',
    seguridad: 'Sécurité',
    idioma: 'Langue',
    galeria: 'Galerie',
    acerca_de: 'À propos',
    terminos: 'Conditions',
    exportar: 'Exporter les données',
    modo_oscuro: 'Mode Sombre',
    modo_claro: 'Mode Clair',
    cerrar_sesion: 'Se déconnecter',
    actualizar_clave: 'Mettre à jour le mot de passe',
    zona_peligro: 'Zone de danger',
    eliminar_cuenta: 'Supprimer le compte définitivement',

    // Journal
    diario_titulo: 'Comment se passe votre journée ?',
    diario_placeholder: 'Dites-moi quelque chose...',
    diario_sueno: 'Heures de sommeil',
    diario_animo: 'Humeur',
    diario_multimedia: 'Multimédia',

    // Stats
    stats_titulo: 'Votre progrès',
    stats_animo_medio: 'Humeur moyenne',
    stats_sueno_medio: 'Sommeil moyen',
    stats_racha_max: 'Série maximale',

    // Meditation
    med_titulo: 'Un moment de calme',
    med_comenzar: 'Commencer la session',
    med_finalizada: 'Session complétée !',
    med_minutos: 'Minutes',
    med_tecnica: 'Technique de respiration',
    med_musica: 'Musique d\'ambiance',

    // Stats Tooltips
    tooltip_comparativa: 'Affiche votre humeur moyenne actuelle et comment elle a changé par rapport à la période précédente, ainsi que vos meilleures séries.',
    tooltip_consistencia: 'Carte thermique qui visualise les jours où vous avez complété chacune de vos habitudes actives.',
    tooltip_impacto: 'Compare votre niveau d\'humeur les jours où vous respectez une habitude (ligne bleue) par rapport à ceux où vous ne le faites pas (ligne dorée), afin d\'identifier les routines qui améliorent le plus votre bien-être. Plus la ligne bleue est éloignée, plus l\'impact positif est grand.',
    tooltip_bienestar: 'Graphique linéaire montrant l\'évolution quotidienne de votre humeur au fil du temps.',
    tooltip_clima: 'Distribution en pourcentage de vos humeurs (de terrible à géniale) au cours de la période sélectionnée.',
    tooltip_descanso: 'Analyse la relation entre vos heures de sommeil et votre humeur. La taille du point indique le niveau d\'humeur.',
    tooltip_paz: 'Suivi de vos minutes de méditation quotidiennes et des techniques de respiration les plus utilisées.',

    // --- LANDING PAGE ---
    landing_nav_iniciar: 'Se connecter',
    landing_nav_empezar: 'Commencer',
    landing_hero_mejor: 'Votre meilleure version.',
    landing_hero_dia: 'Chaque jour.',
    landing_hero_desc: 'Journal émotionnel, habitudes gamifiées, méditation et statistiques avancées sur une seule plateforme.',
    landing_hero_gratis: 'Commencer gratuitement',
    landing_hero_cuenta: 'J\'ai déjà un compte',
    landing_hero_tarjeta: 'Aucune carte requise',
    landing_features_titulo: 'Tout ce dont vous avez besoin',
    landing_features_subtitulo: '6 modules intégrés. Une seule plateforme. Zéro friction.',
    landing_feat_diario_title: 'Journal Émotionnel',
    landing_feat_diario_desc: 'Enregistrez votre humeur, vos pensées et vos heures de sommeil chaque jour. Ajoutez des photos et des notes vocales.',
    landing_feat_habitos_title: 'Habitudes Gamifiées',
    landing_feat_habitos_desc: 'Créez des habitudes, des tâches quotidiennes et des tâches. Gagnez de l\'XP en les complétant et maintenez vos séries au maximum.',
    landing_feat_stats_title: 'Statistiques Intelligentes',
    landing_feat_stats_desc: 'Corrélations humeur-sommeil, constance des habitudes et tendances avec des graphiques interactifs.',
    landing_feat_med_title: 'Méditation Guidée',
    landing_feat_med_desc: 'Techniques de respiration et sons d\'ambiance. Minuteur intégré et suivi des sessions.',
    landing_feat_cal_title: 'Calendrier Visuel',
    landing_feat_cal_desc: 'Consultez votre historique jour après jour avec une carte thermique des émotions et des résumés quotidiens.',
    landing_feat_ranks_title: 'Système de Ligues',
    landing_feat_ranks_desc: 'De "Sans rang" à "Rubis I". Élevez-vous dans la hiérarchie des ligues grâce à votre discipline.',
    landing_intel_tag: 'Intelligence des Données',
    landing_intel_titulo_1: 'Vos données racontent une ',
    landing_intel_titulo_2: 'histoire',
    landing_intel_desc: 'Découvrez comment votre sommeil affecte votre humeur, quelles habitudes vous rendent plus productif et quels sont vos schémas émotionnels au fil du temps.',
    landing_intel_bullet_1: 'Corrélation entre sommeil et humeur',
    landing_intel_bullet_2: 'Cartes thermiques de constance des habitudes',
    landing_intel_bullet_3: 'Analyse des tendances par période',
    landing_intel_bullet_4: 'Statistiques comparatives dynamiques',
    landing_gami_titulo_1: 'S\'améliorer dans la ',
    landing_gami_titulo_2: 'Vraie Vie',
    landing_gami_desc: 'Traitez votre vie comme un RPG. Complétez des habitudes, gagnez de l\'XP et montez de ligue.',
    landing_gami_xp_title: 'Gagnez de l\'XP',
    landing_gami_xp_desc: 'Chaque habitude complétée vous récompense par des points d\'expérience.',
    landing_gami_liga_title: 'Montez de niveau',
    landing_gami_liga_desc: 'Accumulez de l\'XP pour progresser à travers 9 ligues uniques.',
    landing_gami_racha_title: 'Gardez vos séries',
    landing_gami_racha_desc: 'La constance est la clé. Vos séries boostent votre motivation.',
    landing_gami_unete: 'Rejoignez la compétition',
    landing_cta_titulo: 'Commencez aujourd\'hui.',
    landing_cta_desc: 'Votre meilleure version est à portée de clic.',
    landing_cta_crear: 'Créer mon compte',
    landing_footer_acerca: 'À propos du projet',
    landing_footer_terminos: 'Conditions',
    landing_footer_error: 'Signaler une erreur',
    landing_modal_acerca_titulo: 'À propos du projet',
    landing_modal_mision_title: 'Notre Mission',
    landing_modal_mision_desc: 'ImproveMe est une plateforme complète conçue pour faciliter la connaissance de soi et la croissance personnelle. Elle est née du besoin d\'avoir un espace privé et sécurisé pour enregistrer non seulement ce que nous faisons, mais comment nous nous sentons, aidant ainsi à identifier les schémas de comportement et à améliorer notre qualité de vie jour après jour.',
    landing_modal_chars_title: 'Caractéristiques Principales',
    landing_modal_chars_1: 'Enregistrement quotidien des émotions et des pensées.',
    landing_modal_chars_2: 'Suivi des habitudes saines (sommeil, méditation, etc.).',
    landing_modal_chars_3: 'Support multimédia : enregistrez vos souvenirs en voix et en image.',
    landing_modal_chars_4: 'Analyse des progrès grâce à des statistiques détaillées.',
    landing_modal_tec_title: 'Technologie',
    landing_modal_tec_desc: 'Ce projet a été développé à l\'aide de technologies modernes telles que React pour le frontend, Tailwind CSS pour un design premium, et Node.js avec Prisma pour une gestion des données efficace et sécurisée.',
    landing_modal_footer: 'ImproveMe © 2026 · Votre meilleure version commence aujourd\'hui',
    landing_modal_term_titulo: 'Termes et Conditions',
    landing_modal_term_1_title: '1. Acceptation des Conditions',
    landing_modal_term_1_desc: 'En utilisant ImproveMe, vous acceptez de respecter ces conditions. Cette application est conçue pour la croissance personnelle et le suivi des habitudes.',
    landing_modal_term_2_title: '2. Confidentialité des Données',
    landing_modal_term_2_desc: 'Vos journaux quotidiens, audios et images sont stockés de manière sécurisée. ImproveMe ne partage pas vos informations personnelles avec des tiers sans votre consentement explicite.',
    landing_modal_term_3_title: '3. Utilisation Responsable',
    landing_modal_term_3_desc: 'Vous acceptez d\'utiliser l\'application de manière constructive. Le contenu multimédia téléchargé doit respecter les règles de conduite et les lois en vigueur.',
    landing_modal_term_4_title: '4. Propriété Intellectuelle',
    landing_modal_term_4_desc: 'Toute la propriété intellectuelle de l\'application ImproveMe appartient à ses développeurs. Le contenu que vous téléchargez reste le vôtre.',
    landing_modal_term_5_title: '5. Modifications',
    landing_modal_term_5_desc: 'Nous nous réservons le droit de modifier ces conditions à tout moment. Vous serez informé de tout changement important.',
    landing_modal_term_act: 'Dernière mise à jour : 22 avril 2026',
    landing_modal_err_titulo: 'Signaler une erreur',
    landing_modal_err_sub: 'Aidez-nous à améliorer ImproveMe',
    landing_modal_err_sis: 'Informations sur le Système',
    landing_modal_err_nav: 'Navigateur',
    landing_modal_err_plat: 'Plateforme',
    landing_modal_err_res: 'Résolution',
    landing_modal_err_idioma: 'Langue',
    landing_modal_err_inc: 'Description de l\'incident',
    landing_modal_err_placeholder: 'Décrivez en détail ce que vous faisiez et quelle erreur vous avez détectée...',
    landing_modal_err_nota: 'Lors de l\'envoi, un rapport sera généré pour l\'administration de la plateforme avec ces données techniques jointes.',
    landing_modal_err_btn: 'Envoyer le Rapport',
    landing_modal_err_enviando: 'Envoi en cours...',
    landing_modal_err_enviado: 'Envoyé !',

    // --- AUTENTICACIÓN ---
    auth_volver: 'Retour',
    auth_tema_claro: 'Passer en mode clair',
    auth_tema_oscuro: 'Passer en mode sombre',
    auth_bienvenido: 'Bon retour',
    auth_inicia: 'Connectez-vous pour continuer',
    auth_crea: 'Créez votre compte',
    auth_viaje: 'Commencez votre voyage d\'amélioration',
    auth_separador: 'ou continuez avec',
    auth_usuario: 'Nom d\'utilisateur',
    auth_usuario_placeholder: 'Votre alias',
    auth_email: 'E-mail',
    auth_email_placeholder: 'votre@email.com',
    auth_pass: 'Mot de passe',
    auth_pass_placeholder: '••••••••',
    auth_btn_entrar: 'Entrer dans ImproveMe',
    auth_btn_crear: 'Créer un compte',
    auth_cargando: 'Traitement en cours...',
    auth_no_cuenta: 'Vous n\'avez pas de compte ?',
    auth_ya_miembro: 'Déjà membre ?',
    auth_registrate: 'Inscrivez-vous ici',
    auth_inicia_link: 'Se connecter',
    auth_error_credenciales: 'L\'e-mail et le mot de passe sont obligatoires',
    auth_error_registro: 'Tous les champs sont obligatoires',
    auth_error_pass_corta: 'Le mot de passe doit comporter au moins 8 caractères',
    auth_error_sesion_exp: 'Session expirée',
    auth_error_login: 'Erreur lors de la connexion',
    auth_error_singup: 'Erreur lors de l\'inscription',
    auth_error_sinc: 'Erreur de synchronisation des données',
    auth_error_google: 'Erreur lors de la connexion avec Google',
  }
};

export function ProveedorIdioma({ children }) {
  const [idioma, setIdioma] = useState(() => {
    return localStorage.getItem('improveme_idioma') || 'es';
  });

  useEffect(() => {
    localStorage.setItem('improveme_idioma', idioma);
  }, [idioma]);

  const t = (key) => traducciones[idioma][key] || key;

  return (
    <ContextoIdioma.Provider value={{ idioma, setIdioma, t }}>
      {children}
    </ContextoIdioma.Provider>
  );
}

export function useIdioma() {
  return useContext(ContextoIdioma);
}
